In [3]:
import numpy as np

rng = np.random.default_rng(42)

**NumPy** - библиотека для работы с массивами чисел: векторами, матрицами, таблицами числовых признаков.

**NumPy** позволяет делать операции сразу над всем массивом, без ручных циклов Python.

**NumPy** нужен для эффективной работы с числовыми массивами и матрицами. Он позволяет выполнять операции векторно, без явных Python-циклов, и является базой для многих библиотек аналитики и машинного обучения.

Зачем это аналитику

1. Быстрее считать на больших данных
NumPy написан на оптимизированном C под капотом, поэтому операции над массивами работают быстрее, чем обычные Python-циклы.
2. Удобно работать с матрицами
Например:
arr.mean(axis=0)  # среднее по столбцам
arr.mean(axis=1)  # среднее по строкам
3. Маски и фильтрация
arr[arr > 0]
выберет только положительные элементы.
4. Это основа pandas, scipy, sklearn
Много аналитических библиотек внутри опираются на NumPy. Даже если ты чаще работаешь в pandas, под ним часто лежат NumPy-массивы.
5. На собеседовании могут просить “без циклов”
Например:
Найти седловую точку в матрице через NumPy без циклов.

Это проверяет, понимаешь ли ты векторизацию, axis, маски и broadcasting.

## Задача 1: Axis

Дан массив.

Нужно посчитать:
1. максимум по каждой строке;
2. максимум по каждому столбцу;
3. среднее по каждой строке;
4. сумму по каждому столбцу.

In [6]:
arr = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [7]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
arr_rand = rng.integers(0, 10, size = (3, 4))

In [5]:
arr_rand

array([[0, 7, 6, 4],
       [4, 8, 0, 6],
       [2, 0, 5, 9]])

### 1. Максимум по каждой строке

In [9]:
print(f"for the first matrix: {arr.max(axis = 1)}")
print(f"for the second matrix: {arr_rand.max(axis = 1)}")

for the first matrix: [3 6 9]
for the second matrix: [7 8 9]


### 2. Минимум по каждому столбцу

In [10]:
print(f"for the first matrix: {arr.min(axis = 0)}")
print(f"for the second matrix: {arr_rand.min(axis = 0)}")

for the first matrix: [1 2 3]
for the second matrix: [0 0 0 4]


### 3. Среднее по каждой строке

In [12]:
print(f"for the first matrix: {arr.mean(axis = 1)}")
print(f"for the second matrix: {arr_rand.mean(axis = 1)}")

for the first matrix: [2. 5. 8.]
for the second matrix: [4.25 4.5  4.  ]


### 4. Сумма по каждому столбцу

In [13]:
print(f"for the first matrix: {arr.sum(axis = 0)}")
print(f"for the second matrix: {arr_rand.sum(axis = 0)}")

for the first matrix: [12 15 18]
for the second matrix: [ 6 15 11 19]


## Задача 2: Маски

**Маска в NumPy** — это массив из True / False, который показывает, какие элементы подходят под условие.

Дан массив.

Нужно:
1. создать булеву маску, где элементы меньше 0;
2. посчитать, сколько отрицательных элементов в массиве;
3. заменить все отрицательные элементы на 0;
4. отдельно сделать вариант, где исходный arr не меняется.

In [49]:
arr = np.array([
    [1, -2, 3],
    [-4, 5, 6],
    [7, 8, -9]
])

In [50]:
arr

array([[ 1, -2,  3],
       [-4,  5,  6],
       [ 7,  8, -9]])

In [41]:
arr_rand = rng.integers(-5, 10, size = (3, 4))

In [42]:
arr_rand

array([[ 7,  7, -1,  4],
       [-3,  6,  5,  0],
       [-4,  9,  1,  8]])

### 1. Cоздать булеву маску, где элементы меньше 0

In [43]:
print(f"for the first matrix: {arr < 0}")
print(f"for the second matrix: {arr_rand < 0}")

for the first matrix: [[False  True False]
 [ True False False]
 [False False  True]]
for the second matrix: [[False False  True False]
 [ True False False False]
 [ True False False False]]


### 2. Посчитать, сколько отрицательных элементов в массиве

In [44]:
print(f"for the first matrix: {(arr < 0).sum()}")
print(f"for the second matrix: {(arr_rand < 0).sum()}")

for the first matrix: 3
for the second matrix: 3


### 3. Заменить все отрицательные элементы на 0

In [28]:
arr[arr < 0] = 0

In [29]:
arr

array([[1, 0, 3],
       [0, 5, 6],
       [7, 8, 0]])

In [31]:
arr_rand[arr_rand < 0] = 0

In [32]:
arr_rand

array([[6, 6, 5, 6],
       [2, 0, 7, 1],
       [2, 0, 0, 8]])

### 4. Отдельно сделать вариант, где исходный arr не меняется

In [51]:
arr_copy = arr.copy()
arr_rand_copy = arr_rand.copy()

In [52]:
arr_copy[arr_copy < 0] = 0

In [53]:
arr_copy

array([[1, 0, 3],
       [0, 5, 6],
       [7, 8, 0]])

In [57]:
arr

array([[ 1, -2,  3],
       [-4,  5,  6],
       [ 7,  8, -9]])

In [55]:
arr_new = np.where(arr < 0, 0, arr)

In [56]:
arr_new

array([[1, 0, 3],
       [0, 5, 6],
       [7, 8, 0]])

## Задача 3: np.where и категории

Дан массив оценок пользователей от 0 до 100:

In [79]:
scores = rng.integers(0, 101, 8)

In [89]:
scores = np.array([95, 67, 82, 40, 76, 100, 58, 73])

In [90]:
scores

array([ 95,  67,  82,  40,  76, 100,  58,  73])

Нужно:
1. создать массив passed, где будет 1, если оценка >= 70, иначе 0;
2. создать массив labels, где:
   - "high", если оценка >= 85;
   - "medium", если оценка от 70 до 84;
   - "low", если оценка ниже 70;
3. посчитать, сколько пользователей в каждой категории.

### 1. Создать массив passed

In [91]:
passed = np.where(scores >= 70, 1, 0)

In [92]:
passed

array([1, 0, 1, 0, 1, 1, 0, 1])

### 2. Создать массив labels

In [93]:
labels = np.where(scores < 70, 'low', np.where(scores >= 85, 'high', 'medium'))

In [94]:
labels

array(['high', 'low', 'medium', 'low', 'medium', 'high', 'low', 'medium'],
      dtype='<U6')

### 3. Посчитать, сколько пользователей в каждой категории (в labels)

In [98]:
categories, counts = np.unique(labels, return_counts = True)

In [104]:
np.unique(labels)

array(['high', 'low', 'medium'], dtype='<U6')

In [100]:
result = dict(zip(categories, counts))

In [101]:
result

{np.str_('high'): np.int64(2),
 np.str_('low'): np.int64(3),
 np.str_('medium'): np.int64(3)}

In [103]:
result = {str(category): int(count) for category, count in zip(categories, counts)}
result

{'high': 2, 'low': 3, 'medium': 3}

In [102]:
result = {
    "high": int((labels == "high").sum()),
    "medium": int((labels == "medium").sum()),
    "low": int((labels == "low").sum())
}

result

{'high': 2, 'medium': 3, 'low': 3}

## Задача 4: Нормализация столбцов

Дан массив:

In [105]:
X = np.array([
    [10, 100],
    [20, 200],
    [30, 300],
    [40, 400]
])

Нужно создать новый массив X_norm, где каждый столбец нормализован по формуле: **x_norm = (x - mean) / std**

In [107]:
X_norm = (X - X.mean(axis = 0)) / X.std(axis = 0)

In [108]:
X_norm

array([[-1.34164079, -1.34164079],
       [-0.4472136 , -0.4472136 ],
       [ 0.4472136 ,  0.4472136 ],
       [ 1.34164079,  1.34164079]])

In [109]:
X_norm.mean(axis=0)

array([0., 0.])

In [110]:
X_norm.std(axis=0)

array([1., 1.])

## Задача 5: Седловая точка в матрице

Дана матрица:

In [111]:
A = np.array([
    [7, 8, 9],
    [5, 6, 7],
    [3, 4, 5]
])

Нужно найти элемент, который одновременно является:
- минимальным в своей строке;
- максимальным в своем столбце.

Вернуть индексы такого элемента.

In [127]:
row_min_mask = A == A.min(axis = 1, keepdims=True)

In [128]:
row_min_mask

array([[ True, False, False],
       [ True, False, False],
       [ True, False, False]])

In [131]:
col_max_mask = A == A.max(axis = 0, keepdims=True)

In [133]:
col_max_mask

array([[ True,  True,  True],
       [False, False, False],
       [False, False, False]])

In [136]:
saddle_mask = row_min_mask & col_max_mask

In [137]:
indices = np.argwhere(saddle_mask)

In [138]:
indices

array([[0, 0]])

## Задача 6: База массива

Дана матрица:


In [139]:
A = np.array([
    [7, 8, 9],
    [5, 6, 7],
    [3, 4, 5]
])

Важно:
- np.array — это функция NumPy, которая создает NumPy-массив из обычных Python-данных.
- shape — размерность по осям;
- ndim — сколько осей;
- dtype — тип данных внутри массива;
- NumPy-массив обычно хранит элементы одного типа.

### Размерность массива

In [140]:
A.shape

(3, 3)

### Сколько осей

In [141]:
A.ndim

2

### Тип данных внутри массива

In [142]:
A.dtype

dtype('int64')

## Задача 7: argmin, argmax, argwhere

In [145]:
A = np.array([
    [7, 8, 9],
    [5, 6, 7],
    [3, 4, 10]
])

### Возвращает индекс максимума в “плоском” массиве

In [146]:
A.argmax()

np.int64(8)

### Индекс максимума по каждому столбцу

In [147]:
A.argmax(axis = 0)

array([0, 0, 2])

### Индекс максимума по каждой строке

In [148]:
A.argmax(axis = 1)

array([2, 2, 2])

### Возвращает координаты всех элементов, где условие истинно

In [150]:
np.argwhere(A > 5)

array([[0, 0],
       [0, 1],
       [0, 2],
       [1, 1],
       [1, 2],
       [2, 2]])

### Создает новый массив по условию

In [151]:
np.where(A > 5, 1, 0)

array([[1, 1, 1],
       [0, 1, 1],
       [0, 0, 1]])

### Возвращает индексы, где условие True

In [152]:
np.argwhere(A > 5)

array([[0, 0],
       [0, 1],
       [0, 2],
       [1, 1],
       [1, 2],
       [2, 2]])

## Задача 8: Broadcasting

**Broadcasting** — это когда NumPy автоматически “растягивает” массивы совместимых размеров.

Broadcasting буквально можно понимать как “трансляция” или “распространение”.

Смысл названия: NumPy как будто распространяет меньший массив на больший, чтобы выполнить операцию поэлементно.

Например:

In [153]:
X = np.array([
    [10, 100],
    [20, 200],
    [30, 300]
])

In [154]:
means = X.mean(axis=0)

In [155]:
means

array([ 20., 200.])

Когда пишем:

In [156]:
X - means

array([[ -10., -100.],
       [   0.,    0.],
       [  10.,  100.]])

NumPy вычитает: [20, 200] из каждой строки матрицы.

Дан массив покупок клиентов:

In [157]:
purchases = np.array([
    [100, 200, 300],
    [50,  150, 250],
    [400, 100, 500]
])

Строки — клиенты, столбцы — категории товаров.

Дан массив скидок по категориям:

In [159]:
discounts = np.array([0.10, 0.20, 0.15])

Нужно:
1. применить скидки к каждой покупке;
2. получить новый массив final_prices;
3. посчитать итоговую сумму покупок по каждому клиенту после скидки.

In [160]:
final_prices = purchases * (1 - discounts)

In [161]:
final_prices

array([[ 90. , 160. , 255. ],
       [ 45. , 120. , 212.5],
       [360. ,  80. , 425. ]])

In [162]:
final_prices.sum(axis = 1)

array([505. , 377.5, 865. ])